#!/usr/bin/env bash
# Usage: extras/cronwrapper-notify <LOG_FILE_PATH> <EXIT_CODE_PLEX_UPDATE>

# define variables
CONFIG_CRON_NOTIFY="/etc/plexupdate.cron.notify.conf"
LOG_FILE_PATH="${1}"         # DKTODO: use getopt --log-file-path
EXIT_CODE_PLEX_UPDATE="${2}" # DKTODO: use getopt --notify, --error
LOG_FILE_CONTENT="$(cat "${LOG_FILE_PATH}" 2>/dev/null)"
NOTIFY_LEVEL="notify"

if [ "${EXIT_CODE_PLEX_UPDATE}" -ne 0 ] && [ "${EXIT_CODE_PLEX_UPDATE}" -ne 10 ]; then
  NOTIFY_LEVEL="error"
fi

sendPushoverMessage() {
  # define local variables
  local PUSHOVER_API
  local PUSHOVER_TITLE
  local PUSHOVER_ENABLE_HTML
  local PUSHOVER_PRIORITY
  local PUSHOVER_MESSAGE_STATUS_COLOR
  local PUSHOVER_POST_DATA
  local PUSHOVER_MESSAGE

  # set values
  PUSHOVER_API="https://api.pushover.net/1/messages.json"
  PUSHOVER_TITLE="Plex Update"
  PUSHOVER_ENABLE_HTML=1
  PUSHOVER_PRIORITY=0
  PUSHOVER_MESSAGE_STATUS_COLOR="#2E86C1"

  if [ "${NOTIFY_LEVEL}" == 'error' ]; then
    PUSHOVER_PRIORITY=1
    PUSHOVER_TITLE="${PUSHOVER_TITLE}: Error"
    PUSHOVER_MESSAGE_STATUS_COLOR="red"  # DKTODO: colors needs to be tested
  fi

  PUSHOVER_MESSAGE="<b>App:</b> <font color='#e5a00d'><i>plexupdate</i></font><br />"
  PUSHOVER_MESSAGE="${PUSHOVER_MESSAGE}<b>Status:</b> <font color='${PUSHOVER_MESSAGE_STATUS_COLOR}'>${NOTIFY_LEVEL^}</font><br />"
  PUSHOVER_MESSAGE="${PUSHOVER_MESSAGE}<b>Log-output:</b><br /><br />"
  PUSHOVER_MESSAGE="${PUSHOVER_MESSAGE}${LOG_FILE_CONTENT}"

  PUSHOVER_POST_DATA="title=${PUSHOVER_TITLE}&token=${PUSHOVER_TOKEN}&user=${PUSHOVER_USER}&message=${PUSHOVER_MESSAGE}&html=${PUSHOVER_ENABLE_HTML}&priority=${PUSHOVER_PRIORITY}"

  if [ -n "${PUSHOVER_SOUND}" ]; then
    PUSHOVER_POST_DATA="${PUSHOVER_POST_DATA}&sound=${PUSHOVER_SOUND}"
  fi

  HTTP_STATUS_CODE=$(wget --server-response --quiet -O /dev/null --post-data="${PUSHOVER_POST_DATA}" "${PUSHOVER_API}" 2>&1 | grep "HTTP/" | awk '{print $2}')

  if [ "$HTTP_STATUS_CODE" -ne 200 ]; then
    echo "ERROR: Something went wrong on sending pushover message. HTTP status-code is '${HTTP_STATUS_CODE}'" >&2
    exit 255
  fi
}

if [ ! -f ${CONFIG_CRON_NOTIFY} ]; then
  echo "ERROR: You have not configured ${CONFIG_CRON_NOTIFY}" >&2
  exit 255
else
  source ${CONFIG_CRON_NOTIFY}
fi

if [ "${SEND_PUSHOVER}" = "yes" ]; then
  if [ -n "${PUSHOVER_USER}" ] && [ -n "${PUSHOVER_TOKEN}" ]; then
    sendPushoverMessage
  else
    echo "ERROR: Config \"PUSHOVER_USER\" and/or \"PUSHOVER_TOKEN\" missing in ${CONFIG_CRON_NOTIFY}" >&2
    exit 255
  fi
fi
