#!/usr/bin/env bash
# Usage: extras/cronwrapper-notify <LOG_FILE_PATH> <EXIT_CODE_PLEX_UPDATE>

# define variables
CONFIG_CRON_NOTIFY="/etc/plexupdate.cron.notify.conf"
LOG_FILE_PATH="${1}"         # DKTODO: use getopt --log-file-path
EXIT_CODE_PLEX_UPDATE="${2}" # DKTODO: use getopt --notify, --error
LOG_FILE_CONTENT="$(cat "${LOG_FILE_PATH}" 2>/dev/null)"
NOTIFY_LEVEL="notify"

if [ "${EXIT_CODE_PLEX_UPDATE}" -ne 0 ] && [ "${EXIT_CODE_PLEX_UPDATE}" -ne 10 ]; then
  NOTIFY_LEVEL="error"
fi

# DKTODO: message should be improved with server-name:port e.g. link, current server version, new version, ...?

sendPushoverMessage() {
  # define local variables
  local PUSHOVER_API
  local PUSHOVER_TITLE
  local PUSHOVER_ENABLE_HTML
  local PUSHOVER_PRIORITY
  local PUSHOVER_MESSAGE_STATUS_COLOR
  local PUSHOVER_POST_DATA
  local PUSHOVER_MESSAGE

  # set values
  PUSHOVER_API="https://api.pushover.net/1/messages.json"
  PUSHOVER_TITLE="Plex Update"
  PUSHOVER_ENABLE_HTML=1
  PUSHOVER_PRIORITY=0
  PUSHOVER_MESSAGE_STATUS_COLOR="#2E86C1"

  if [ "${NOTIFY_LEVEL}" == 'error' ]; then
    PUSHOVER_PRIORITY=1
    PUSHOVER_TITLE="${PUSHOVER_TITLE}: Error"
    PUSHOVER_MESSAGE_STATUS_COLOR="red" # DKTODO: colors needs to be tested
  fi

  PUSHOVER_MESSAGE="<b>App:</b> <font color='#e5a00d'><i>plexupdate</i></font><br />"
  PUSHOVER_MESSAGE="${PUSHOVER_MESSAGE}<b>Status:</b> <font color='${PUSHOVER_MESSAGE_STATUS_COLOR}'>${NOTIFY_LEVEL^}</font><br />"
  PUSHOVER_MESSAGE="${PUSHOVER_MESSAGE}<b>Log-output:</b><br /><br />"
  PUSHOVER_MESSAGE="${PUSHOVER_MESSAGE}${LOG_FILE_CONTENT}"

  PUSHOVER_POST_DATA="title=${PUSHOVER_TITLE}&token=${PUSHOVER_TOKEN}&user=${PUSHOVER_USER}&message=${PUSHOVER_MESSAGE}&html=${PUSHOVER_ENABLE_HTML}&priority=${PUSHOVER_PRIORITY}"

  if [ -n "${PUSHOVER_SOUND}" ]; then
    PUSHOVER_POST_DATA="${PUSHOVER_POST_DATA}&sound=${PUSHOVER_SOUND}"
  fi

  HTTP_STATUS_CODE=$(wget --server-response --quiet -O /dev/null --post-data="${PUSHOVER_POST_DATA}" "${PUSHOVER_API}" 2>&1 | grep "HTTP/" | awk '{print $2}')

  if [ "$HTTP_STATUS_CODE" -ne 200 ]; then
    echo "ERROR: Something went wrong on sending pushover message. HTTP status-code is '${HTTP_STATUS_CODE}'" >&2
    exit 255
  fi
}

sendDiscordMessage() {
  # define local variables
  local DISCORD_API_ENDPOINT
  local DISCORD_API
  local DISCORD_TITLE
  local DISCORD_COLOR
  local DISCORD_POST_DATA
  local DISCORD_POST_DATA_EMBEDED
  local DATE_NOW_ISO8601 # DKTODO: move this out?
  local DISCORD_FOOTER_TEXT

  # set values
  DISCORD_API_ENDPOINT="https://discordapp.com/api/v6"
  DISCORD_API="${DISCORD_API_ENDPOINT}/channels/${DISCORD_CHANNEL_ID}/messages"
  DISCORD_TITLE="Plex Update"
  # DISCORD_DESCRIPTION="${LOG_FILE_CONTENT}" # DKTODO: disabled for now, need to escape probably
  DISCORD_DESCRIPTION="Some message"        # DKTODO: define message
  DISCORD_COLOR="3447003"
  DATE_NOW_ISO8601=$(date +%Y-%m-%dT%H:%M:%S%z)
  DISCORD_FOOTER_TEXT="Plex Media Server" # DKTODO: a version could be used here
  DISCORD_FOOTER_ICON_URL="https://dl2.macupdate.com/images/icons256/42311.png?d=1535042731"

  # DKTODO: this should look more readable
  # DKTODO: jq would be nice, if its possible to use...
  DISCORD_POST_DATA_EMBEDED='{"title":"'"${DISCORD_TITLE}"'","description":"'"${DISCORD_DESCRIPTION}"'","color":"'"${DISCORD_COLOR}"'","timestamp":"'"${DATE_NOW_ISO8601}"'","footer":{"text":"'"${DISCORD_FOOTER_TEXT}"'", "icon_url":"'"${DISCORD_FOOTER_ICON_URL}"'"}}'
  DISCORD_POST_DATA='{"embed":'${DISCORD_POST_DATA_EMBEDED}'}'

  HTTP_STATUS_CODE=$(wget --server-response --quiet -O /dev/null --header="Authorization: Bot ${DISCORD_BOT_TOKEN}" --header='Content-Type:application/json' --post-data=''"${DISCORD_POST_DATA}"'' "${DISCORD_API}" 2>&1 | grep "HTTP/" | awk '{print $2}')

  if [ "$HTTP_STATUS_CODE" -ne 200 ]; then
    echo "ERROR: Something went wrong on sending discord message. HTTP status-code is '${HTTP_STATUS_CODE}'" >&2
    exit 255
  fi
}

if [ ! -f ${CONFIG_CRON_NOTIFY} ]; then
  echo "ERROR: You have not configured ${CONFIG_CRON_NOTIFY}" >&2
  exit 255
else
  source ${CONFIG_CRON_NOTIFY}
fi

if [ "${SEND_PUSHOVER}" = "yes" ]; then
  if [ -z "${PUSHOVER_USER}" ] || [ -z "${PUSHOVER_TOKEN}" ]; then
    echo "ERROR: Config \"PUSHOVER_USER\" and/or \"PUSHOVER_TOKEN\" missing in ${CONFIG_CRON_NOTIFY}" >&2
    exit 255
  fi
  sendPushoverMessage
fi

if [ "${SEND_DISCORD}" = "yes" ]; then
  if [ -z "${DISCORD_BOT_TOKEN}" ] || [ -z "${DISCORD_CHANNEL_ID}" ]; then
    echo "ERROR: Config \"DISCORD_BOT_TOKEN\" and/or \"DISCORD_CHANNEL_ID\" missing in ${CONFIG_CRON_NOTIFY}" >&2
    exit 255
  fi
  sendDiscordMessage
fi
